### ISSUE TITLE
Two-way audio not working

### ISSUE THREAD

**Issue by rfiorentino1** [potmat/homebridge-google-nest-sdm#105]
Hi,

After following all the steps in the installation process etc, my Nest Doorbell appears in the home app, and I can view it/hear it's audio. However, when I press the talk button in the home app, I can't talk through the doorbell. What am I missing? Also, there doesn't appear to be any streaming logs, so can't troubleshoot from there.

**Comment by potmat** [comment]
Unfortunately the SDM API does not support two way audio.

**Comment by rfiorentino1** [comment]
Really? That's pretty dumb on Google's part lol. But that also completely defeats the purpose of this plug-in for me… Do you know of any other APIs that do support 2-way, for the new cameras?

**Comment by potmat** [comment]
@rfiorentino1:  There is no other officially supported API for accessing Nest devices.  You can create a feature request to Google here: https://issuetracker.google.com/issues?q=status:open%20componentid:1351014&s=created_time:desc
