### ISSUE TITLE
Accessory out of compliance

### ISSUE THREAD

**Issue by zuhairmahd** [potmat/homebridge-google-nest-sdm#110]
Whenever I enable the google-nest-sdm plugin, I can no longer add the bridge to HomeKit.  This only started last week -- I have otherwise been running the plugin for a few months without any issues.  To troubleshoot and rule out any other plugins:
1. Disabled all HB plugins and re-enabled them one at a time.  The error message was reproducible 100% of the time whenever the nest-sdm plugin was enabled.
2. Added the plugin as a child bridge and got the error message when I tried adding it to my HK setup.
3. Tried on a different machine with a fresh installation with the same result.
4. Examined the logs and the only error message I see is about an illegal value (cooling) which I have seen repeatedly when the setup was functioning.
5. With the plugin disabled, my HK setup is functioning quite nicely.

**Comment by potmat** [comment]
Hi @zuhairmahd, I'm terribly sorry but I haven't the foggiest idea why this is happening to you.  Perhaps if others start having this problem we can get to the bottom of it.

**Comment by zuhairmahd** [comment]
Thanks @potmat. The only thing I haven't done is to recreate the configuration values using a new GCP and SDM projects. I can't see why that might make a difference but it's worth trying I guess ... in the absence of other possibilities

**Comment by zuhairmahd** [comment]
Abandoned the plugin then came back a few months later and everything works. Closing the issue. Thanks again for putting this together.
