### ISSUE TITLE
[error] Empty H.264 RTP packet

### ISSUE THREAD

**Issue by normanmaurer** [potmat/homebridge-google-nest-sdm#13]
First of thanks for all the work! I just tried it with my google nest doorbell (akku) and it seems to work as expected.
That said I see a lot of these logs:

```
1|homebridge  | [1/24/2022, 3:21:22 PM] [homebridge-google-nest-sdm] [sdp @ 0x80cc59000] [error] Empty H.264 RTP packet Flur Doorbell
```

I wonder if there is anything wrong with my setup or if its expected ?

**Comment by potmat** [comment]
Hi @normanmaurer, this is just the verbose logging of ffmpeg, it does not seem to affect playback at all.

**Comment by normanmaurer** [comment]
@potmat ok cool... can I somehow disable this verbosity ? It fills up the logs :)

**Comment by potmat** [comment]
@normanmaurer : Turn off debug mode.
