### ISSUE TITLE
Nest Thermostat - can no longer set temperature via the Home app

### ISSUE THREAD

**Issue by betabob** [potmat/homebridge-google-nest-sdm#137]
Sometime within the last day or so I noticed that I can no longer set the temp on my Nest thermostat via the home app; when I open the device on the home app it displays "off". However, I can still do other things like set Eco mode, and on the main home app screen it still correctly shows the current temp as well as the high/low ranges that were set. In viewing the Homebridge logs I see the following errors:

[1/18/2024, 8:38:04 AM] [homebridge-google-nest-sdm] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 9.5 exceeded minimum of 10. See https://homebridge.io/w/JtMGR for more info.

It looks like this is related to my problem?

**Comment by betabob** [comment]
The above error message seems to get generated anytime that I open up the thermostat device within the Apple Home app.

**Comment by potmat** [comment]
I'm guessing you're in North America where we have been having a cold snap for the last week or so.

What state is your thermostat in when looking in the Nest app?  Does it control both heating and cooling? Is there a threshold set for cooling....

**Comment by betabob** [comment]
Yes, it controls both heating and cooling. I live in Northern California, so I haven't been subject to any temperature extremes. I typically set the thermostat to stay somewhere b/t around 65 and 83 degrees...eco mode is not too different from that as well.

Interestingly enough, I have a 2nd Nest thermostat located in a different house that is connected to my Homebridge and it is controllable via the Apple Home app just fine...and that location is up in the mountains where there is a lot more temperature variation swings.

**Comment by betabob** [comment]
Also, restarting Homebridge doesn't fix the problem :(

**Comment by potmat** [comment]
Very strange.... maybe try clearing your device cache and then restarting? Maybe the device is stuck in a bad state somehow?

**Comment by betabob** [comment]
Kinda doubt that. Over the weekend I upgraded my Homebridge, stopped running it as a Docker container on my Synology NAS and switched over to the Native NAS plugin version....and upgraded to HB 1.7 at the same time. Problem still exists post upgrade, though TBH it's not terribly bothersome to me as I can still control that thermostat via a different Nest plugin.

**Comment by betabob** [comment]
So, it looks like the latest plugin released fixed my issue 👍
