### ISSUE TITLE
Automation based on heating switching modes

### ISSUE THREAD

**Issue by TheBartoMan** [potmat/homebridge-google-nest-sdm#14]
I cant create a Homekit Automation based on when the heating switches off and on?

I need to know when the thermostat has changed to a specific mode? I.E. heating has begun or stopped.

Is this possible please? I only seem to be able to do automation based on it the temperature changes above/below a certain level.

**Comment by potmat** [comment]
Hi @TheBartoMan, I'm not sure.  I don't actually own a HomePod or AppleTV so I don't have any automations setup.

As far as I can tell the plugin is correctly reporting the heating/cooling state.

Perhaps this is a limitation of automations, not of the plugin?

If anyone else does automations please chime in.

**Comment by TheBartoMan** [comment]
As all the information is there regarding the status of the heating? Could one of the tick boxes not be created in the settings to allow this to be reported as a HomeKit Device?

**Comment by potmat** [comment]
@TheBartoMan : Yes the plugin correctly sets the current heating/cooling state.  Beyond that I'm not sure what else I can do.

Perhaps try reaching out on Discord or Reddit to see if others are creating such automations?

**Comment by TheBartoMan** [comment]
when i click the thermostat to see the values, one is "Current Heating Cooling State" - this is either 1 or 0 depending upon if the heating is currently off of on.
Unfortunately, it doesn't appear in HomeKit as an automation option. Would be great if I could do an automations for "When heating is on..."

What file in homebridge stores all these values? Maybe I can find a work around for now.

**Comment by potmat** [comment]
@TheBartoMan : This doesn't seem to be an issue with this plugin but with Homebridge or HomeKit itself.  If you find that the plugin is actually doing something incorrectly I will re-open it.
