### ISSUE TITLE
Feature request: Start stream as soon as motion is detected

### ISSUE THREAD

**Issue by normanmaurer** [potmat/homebridge-google-nest-sdm#15]
I wonder if it would be possible to basically start the stream as soon as a motion (via a person) is detected. This could allow to speedup the opening of the live-view. Basically start a stream and keep it open for a period of time in the "hope" that the user will start to watch the live-stream anyway. 

WDYT ?

**Comment by potmat** [comment]
@normanmaurer:  While this sounds simple in theory, in practice it would be very difficult to achieve. With no one requesting a stream there is nowhere to send the stream "to".  This means the audio/video data would need to be buffered somewhere in a format agnostic fashion such that it could be picked up and transformed for sending the requesting device. Storing a moving buffer of video data in this manner, while theoretically possible, is probably not something I can implement now.
