### ISSUE TITLE
Thermostat Temperature Throttling

### ISSUE THREAD

**Issue by rudiv** [potmat/homebridge-google-nest-sdm#157]
It seems with every increment of a temperature change this is hitting the API which in turn causes rate limits:

```
...
"errors":[{"message":"Rate limited for the SetThermostatTemperatureHeat command for the user.","domain":"global","reason":"rateLimitExceeded"}]}
Entryway Thermostat
```

Would be great if this could throttle the setting of this to the requested value by even 500ms or so to reduce the occurances of this.

**Comment by potmat** [comment]
Duplicate of https://github.com/potmat/homebridge-google-nest-sdm/issues/99

**Comment by rudiv** [comment]
Oops, my bad.
