### ISSUE TITLE
Doorbell feed only displays on iPhone

### ISSUE THREAD

**Issue by litex2x** [potmat/homebridge-google-nest-sdm#161]
**Have you read the [FAQ](https://github.com/potmat/homebridge-google-nest-sdm#faq)?**

Yes

**Have you searched [existing issues](https://github.com/potmat/homebridge-google-nest-sdm/issues?q=is%3Aissue)?**

Yes

**Have you searched [existing discussions](https://github.com/potmat/homebridge-google-nest-sdm/discussions?discussions_q=)?**

Yes

**Describe the bug**
Not sure if this is a widespread problem or just impacting me. For some reason I can only view my doorbell feed on iPhones. I used to be able to view it on my Apple TV 4K and in the Home app on my Macbook.

**Attach Logs**
I don't see any errors in the log. The log seems to indicate the stream is working even though nothing gets displayed.

**Screenshots**
N/A

**Environment**
Running homebridge in a docker container on a Raspberry Pi 4 host.

**Additional context**
N/A

**Comment by potmat** [comment]
Try updating Homebridge and/or NodeJS?

**Comment by litex2x** [comment]
This appears to be a local network issue. Feed displays consistently when I am reaching it outside my LAN. It might have to do with the network config with my homebridge docker container.

**Comment by litex2x** [comment]
For anyone wondering, the fix was to make container use a macvlan network.
