### ISSUE TITLE
Plugin initialization failed, there was a failure with event subscription. Request had insufficient authentication scopes.

### ISSUE THREAD

**Issue by GrumpyGoslin** [potmat/homebridge-google-nest-sdm#17]
Hi, 

I have been having the following issue on start-up. I have checked and re-created everything but I feel like I have missed something.

I suspect it's something around scopes but can't see what the issue might be.

Here is the error

> [28/02/2022, 09:48:06] [homebridge-google-nest-sdm] Plugin initialization failed, there was a failure with event subscription. Did you read the readme: https://github.com/potmat/homebridge-google-nest-sdm#where-do-the-config-values-come-from StatusError: Request had insufficient authentication scopes.
>     at MessageStream._onEnd (/usr/local/lib/node_modules/homebridge-google-nest-sdm/node_modules/@google-cloud/pubsub/src/message-stream.ts:289:20)
>     at MessageStream._onStatus (/usr/local/lib/node_modules/homebridge-google-nest-sdm/node_modules/@google-cloud/pubsub/src/message-stream.ts:330:12)
>     at ClientDuplexStreamImpl.<anonymous> (/usr/local/lib/node_modules/homebridge-google-nest-sdm/node_modules/@google-cloud/pubsub/src/message-stream.ts:184:38)
>     at Object.onceWrapper (node:events:640:26)
>     at ClientDuplexStreamImpl.emit (node:events:520:28)
>     at Object.onReceiveStatus (/usr/local/lib/node_modules/homebridge-google-nest-sdm/node_modules/@grpc/grpc-js/src/client.ts:675:16)
>     at Object.onReceiveStatus (/usr/local/lib/node_modules/homebridge-google-nest-sdm/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
>     at /usr/local/lib/node_modules/homebridge-google-nest-sdm/node_modules/@grpc/grpc-js/src/call-stream.ts:323:24
>     at processTicksAndRejections (node:internal/process/task_queues:78:11) {
>   code: 7,
>   details: 'Request had insufficient authentication scopes.',
>   metadata: Metadata {
>     internalRepr: Map(3) {
>       'google.rpc.errorinfo-bin' => [Array],
>       'grpc-status-details-bin' => [Array],
>       'www-authenticate' => [Array]
>     },
>     options: {}
>   }
> }

**Comment by potmat** [comment]
@GrumpyGoslin : Sorry I didn't have time to respond this week, I'm guessing you got it figured out?

**Comment by mlavio829** [comment]
what was the solution to this?

**Comment by mainto** [comment]
@GrumpyGoslin Could you explain how to resolve this issue?
