### ISSUE TITLE
Ram bug

### ISSUE THREAD

**Issue by GillesWi** [potmat/homebridge-google-nest-sdm#170]
[HDS ::ffff:192.168.0.228] Recording download stream 1 is still awaiting generator although stream was closed 10s ago! This is a programming mistake by the camera implementation which prevents freeing up resources.

Rpi 4b crashes after a few days because memory is filled up... could it be because of this? Only in the latest versions

**Comment by Abcmsaj** [comment]
I’ve got this too. It’ll open a new instance of ffmpeg on my Mac every time this error occurs and so I’ve ended up having to kill 15-20 ffmpeg processes at once to free up memory

**Comment by ShadowRegent** [comment]
I'm also having this issue and have many ffmpeg processes stuck running.

**Comment by potmat** [comment]
Duplicate of https://github.com/potmat/homebridge-google-nest-sdm/issues/150
