### ISSUE TITLE
Access Token Error 

### ISSUE THREAD

**Issue by arsenal6** [potmat/homebridge-google-nest-sdm#172]
**Have you read the [FAQ](https://github.com/potmat/homebridge-google-nest-sdm#faq)?**

Yes

**Have you searched [existing issues](https://github.com/potmat/homebridge-google-nest-sdm/issues?q=is%3Aissue)?**

Yes

**Have you searched [existing discussions](https://github.com/potmat/homebridge-google-nest-sdm/discussions?discussions_q=)?**

Yes

**Describe the bug**

Using the "link your account" function returns an error

https://nestservices.google.com/partnerconnections/project-id/auth?redirect_uri=https://www.google.com&access_type=offline&prompt=consent&client_id=oauth2-client-id&response_type=code&scope=https://www.googleapis.com/auth/sdm.service

**Attach Logs**
Enable debug mode in Homebridge and post logs from around when the error is happening.  Especially if the error is video failing to play.

**Screenshots**

![image](https://github.com/potmat/homebridge-google-nest-sdm/assets/4634460/650e4dc0-7c60-4d17-b972-c9d0a29c46c6)

**Environment**
Provide some information about your Homebridge config.  What device it is running on, if it's in bridged mode etc.  Anything that may be relevant.

**Additional context**

**Comment by kenijo** [comment]
How did you solve this issue?
