### ISSUE TITLE
Doorbell motion for packages

### ISSUE THREAD

**Issue by krayzie32** [potmat/homebridge-google-nest-sdm#19]
I'm not seeing Doorbell motion for packages alerts. Is this a limitation of their API? Thanks!

**Comment by potmat** [comment]
Hi @krayzie32, the SDM API does not fire any events related to packages.  Here is the full list of events it supports:

wired: https://developers.google.com/nest/device-access/api/doorbell#handle_doorbell_and_camera_events
battery: https://developers.google.com/nest/device-access/api/doorbell-battery#handle_doorbell_and_camera_events
