### ISSUE TITLE
PubSub Subscription ID

### ISSUE THREAD

**Issue by bradhs** [potmat/homebridge-google-nest-sdm#2]
There was a failure with event subscription. Did you read the readme: https://github.com/potmat/homebridge-google-nest-sdm/blob/master/README.md StatusError: Invalid resource name given 

I confirmed I have the right resource name, and that it is enabled but it still fails.

EDIT: You have to manually create a subscription then use that in the config.

**Comment by bradhs** [comment]
Nevermind, found it..

**Comment by bradhs** [comment]
I was able to test adding a topic but for some reason still not working.

**Comment by parkr** [comment]
I ran into this too. It required me to run through this: https://developers.google.com/nest/device-access/subscribe-to-events#create_a_pull_subscription
