### ISSUE TITLE
Plugin initialization failed, there was a failure with event subscription. Did you read the readme: https://github.com/potmat/homebridge-google-nest-sdm#where-do-the-config-values-come-from StatusError: User not authorized to perform this action.

### ISSUE THREAD

**Issue by Hackintoshbigsur** [potmat/homebridge-google-nest-sdm#26]
I Don't Know how to fix this is did use the second Gcpproject id please help!

**Comment by potmat** [comment]
"User not authorized to perform this action."

That's a new one... So as the message says, did you read the readme and follow the steps, especially the "ONE IMPORTANT DIFFERNCE" part?

**Comment by Hackintoshbigsur** [comment]
Yes I did, multiple times and I also redid the subscription, and as a result I can’t use hksv, and the thermostat is very buggy.

**Comment by potmat** [comment]
For the subscription field you put something like "projects/your-gcp-project-id/subscriptions/your-subscription-id" correct?  Not just the ID part?

**Comment by Hackintoshbigsur** [comment]
Yes, I copied the subsciption Javed Bakhrani that looked and use the same format.

**Comment by potmat** [comment]
Javed Bakhrani?

At any rate, I'm terribly sorry but I have no idea what's happening here.  Perhaps there is something unique about your Cloud Console configuration.  Do you have multiple projects on cloud console or something like this? Have you done anything on cloud console other than what's in the getting started guide?

**Comment by Hackintoshbigsur** [comment]
Sorry thats an auto type feature, when i type "name" it changes it, so sorry i meant "name".

**Comment by Hackintoshbigsur** [comment]
Do I need to change it from pull or push in Pub/Sub?

**Comment by potmat** [comment]
According to the docs it should be a pull subscription: https://developers.google.com/nest/device-access/subscribe-to-events#create_a_pull_subscription

**Comment by Hackintoshbigsur** [comment]
Ok, so I redid this part and redid and it is still telling me user not authorized.

**Comment by Hackintoshbigsur** [comment]
Ok, So Another update, the thermostat is reading 85 Degrees, and the user not authorized error is not gone, I have tried doing the whole process over again.

**Comment by potmat** [comment]
Sorry @Hackintoshbigsur, I'm not sure there's anything I can do.  The users of this plugin now number well into the thousands and no one else has reported such an issue, so you must be doing _something_ differently.  Unfortunately without me standing over your shoulder watching I have no way to know what that is.

**Comment by Hackintoshbigsur** [comment]
Ok, I'll try this with another account if it does not work I'll have to settle for something else.

**Comment by jaxfry** [comment]
I am also encountering this error.

**Comment by Hackintoshbigsur** [comment]
I am still encountering this issue after re-doing the steps *preciesly* like 7 times over 2 weeks.

**Comment by Hackintoshbigsur** [comment]
I had to create a new event subscription with AllUsers Prinicple Permission enabled with the topic ID of the Nest SDM pub/sub.
