### ISSUE TITLE
Status and Notifications are not coming through

### ISSUE THREAD

**Issue by casperstorm** [potmat/homebridge-google-nest-sdm#28]
First of all, thanks for a great plugin. Much appreciated.

I recently bought a Nest Doorbell (battery), and just got it connected through this plugin.
It is... almost... working: i see it in the dashboard (with a google `G` placeholder) and pressing it shows a live view. However, no notification or chime is coming through the `Home` app, only through `Google Home`.
Under `Status and Notifications` most is enabled, also `Doorbell notifications` and `Doorbell Chime`.

Anyone have a suggestion to what the issue might be?

**EDIT**

I missed the logs in Homebridge. The error was:

> Plugin initialization failed, there was a failure with event subscription. Did you read the readme: https://github.com/potmat/homebridge-google-nest-sdm#where-do-the-config-values-come-from StatusError: Cloud Pub/Sub API has not been used in project REDACTED before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/pubsub.googleapis.com/overview?project=REDACTED then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

This solved it.

**Comment by potmat** [comment]
Thanks for posting the solution @casperstorm !
