### ISSUE TITLE
Google Doorbell shown as camera

### ISSUE THREAD

**Issue by Joost1985** [potmat/homebridge-google-nest-sdm#33]
Hello,

I have installed a Google Doorbell and it appears neatly in Homekit. However, he is not shown as a doorbell, but as a camera. So I can't make automations and I don't see a doorbell button in Homekit. Am I doing something wrong or does the plugin not support this?

**Comment by potmat** [comment]
The plugin fully supports doorbells, I have one myself and it works fine.  This is very strange and I can't really account for it.  Perhaps if you enable debug mode and show me the logs right after restarting Homebridge that may be helpful.

**Comment by Joost1985** [comment]
Thanks for your reply. I have since exchanged the Google doorbell for a Eufy. So this issue can be closed.
