### ISSUE TITLE
Thermostat threshold values when mode is HEAT or COOL (not Auto or Eco)

### ISSUE THREAD

**Issue by ghkites** [potmat/homebridge-google-nest-sdm#34]
When I'm set to HEAT or COOL mode and I ask Siri what the thermostat is set to, the response is along the lines of _"The thermostat is on, but not actively heating or cooling.  It's set to cool to 10C."_  If I'm in HEAT mode, it responds with _"It's set to heat to 0C"_.  In the Home app, everything looks fine - I see the correct target temperature, it's just the verbal / text responses from Siri (both on my phone and HomeHub) that aren't right.

The 10C and 0C values for COOL/HEAT appear to the default values for the CoolingThresholdTemperature and HeatingThresholdTemperature characteristics, respectively.

I switched to ECO and adjusted my thresholds and that changed the responses when I switched back to HEAT or COOL mode (in COOL mode, it now says "24" instead of "10" (default), or "22" (my target)).  It looks like the values for those characteristics get cached, even if you switch away from a mode that uses the thresholds.  Even if they were unset somehow, I'm not sure if the responses from Siri would default back to the 10 and 0 default values (not sure how to test this).  Maybe the target and cooling threshold need to match in COOL, and target and heating threshold for HEAT?  Just guessing / thinking out loud.

Thanks,
GH

**Comment by potmat** [comment]
Hi @ghkites, very interesting, perhaps Siri does some caching?  However it sounds like things are now working ok unless I'm mistaken.

**Comment by ghkites** [comment]
Still having an issue with it giving the threshold temperature even when it COOL or HEAT mode (rather than heat-cool or eco), I was just able to influence what that value was.

I have some suspicion that Siri works a bit differently than the Home app.

My current best guess is that no matter the mode, Siri will use the cooling or heating threshold characteristic value as opposed to the target temperature.  I’m wondering if the getters for the thresholds should always return values, but with added logic to check the mode and return target for heat or cool modes and threshold value for eco, heat-cool/auto modes.

I also noticed that if I ask Siri on my phone “What is my thermostat set to”, it will complain about accessories not responding, whereas the HomeHub will respond (albeit with the incorrect temperature).  Perhaps the HomeHub caches whereas mobile devices don’t.

I’m hoping to be able to find some time to mess with this a bit more next week, but we’ll see.

**Comment by potmat** [comment]
Hi @ghkites, I've reproduced this behaviour myself, Siri always tells me the heat is 0C or 10C.  I don't know yet why this is happening... I'll need to investigate more.

**Comment by potmat** [comment]
Try the latest release 1.1.7

**Comment by ghkites** [comment]
Initial results seem good so far!  All of my devices respond to the prompt now, including my HomeHub, iPad, iPhone, Watch and MacBook.  The only peculiar thing is that Siri on macOS responds saying that the thermostat is "set between 21°C and 21°C".  All other devices respond properly with "It's set to heat to 21°C".

With that said, I'm not really concerned with the macOS side - it could very well be a difference in macOS versus all of the other mobile (or mobile-ish) OSs.

Thanks!

**Comment by potmat** [comment]
@ghkites : You're welcome!
