### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by JanosTurk** [potmat/homebridge-google-nest-sdm#35]
I can not authorize the account. 
Google complaining to 

Authorisation Error
Error 400: redirect_uri_mismatch

I have no idea what is wrong with this. 

The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.
If you’re the app developer, make sure that these request details comply with Google policies.

    redirect_uri: https://www.google.com

**Comment by potmat** [comment]
Hi @JanosTurk, this is an error you receive in the Homebridge logs? Or when you're following the getting started guide?

**Comment by JanosTurk** [comment]
The first part of the setup guide is fine. When I try to authorise my sandbox to get the refresh token and subscription id the google page comes up. 
So I opened this URL:

https://nestservices.google.com/partnerconnections/project-id/auth?redirect_uri=https://www.google.com&access_type=offline&prompt=consent&client_id=oauth2-client-id&response_type=code&scope=https://www.googleapis.com/auth/sdm.service+https://www.googleapis.com/auth/pubsub

of course with my details. Assigned my gmail account as requested. Allowed permission to have access to my door entry. Then came up this error message above…

**Comment by JanosTurk** [comment]
I wasted 12 hours on this one. I have done every single step again and again and I'm not able to authorize my Google Account. I gave up on this... It does not work or the documentation is wrong. 

Access blocked: Door’s request is invalid

You can’t sign in because Door sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://developers.google.com/identity/protocols/oauth2/web-server#authorization-errors-redirect-uri-mismatch)
If you are a developer of Door, see [error details](https://accounts.google.com/).
Error 400: redirect_uri_mismatch

**Comment by potmat** [comment]
I'm sorry you're having so much trouble @JanosTurk, however I really am not able to offer support for the Google, only for issues with the plugin itself.  As the FAQ says:

"The Nest plugin for Home Assistant uses much the same process (don't forget the ["ONE IMPORTANT DIFFERENCE"](https://github.com/potmat/homebridge-google-nest-sdm#where-do-the-config-values-come-from) section above). It has an [illustrated guide](https://www.home-assistant.io/integrations/nest/) that you may find helpful. You can also try reaching out to others on [Discord](https://discord.gg/kqNCe2D) or [Reddit](https://www.reddit.com/r/homebridge/), some people there may be able to help."
