### ISSUE TITLE
CurrentHeatingCoolingState:OFF  not updating

### ISSUE THREAD

**Issue by rpersche** [potmat/homebridge-google-nest-sdm#37]
Hello, 

I think I found a bug in this code. When the heating or cooling stops, the value of "converted" is 0 (this.platform.Characteristic.CurrentHeatingCoolingState.OFF), and thus it does not go into the if statement to update the status. 

```
    private handleCurrentHeatingCoolingStateUpdate(status: Traits.HvacStatusType) {
        this.log.debug('Update CurrentHeatingCoolingState:' + status, this.accessory.displayName);
        let converted = this.convertHvacStatusType(status);
        if (converted)
            this.service.updateCharacteristic(this.platform.Characteristic.CurrentHeatingCoolingState, converted);
    }
```

```
   if (converted !== null) 
```
should fix it.

**Comment by potmat** [comment]
Hmmm... you could be right.  However my thermostat always reports on/off correctly, I'll take a look.

**Comment by potmat** [comment]
Hi @rpersche, try the new version 1.1.6

**Comment by rpersche** [comment]
@potmat thanks. I will when I am back from my holiday travels.

**Comment by rpersche** [comment]
@potmat it's working great now. Thanks.

**Comment by potmat** [comment]
You're very welcome.
