### ISSUE TITLE
not working : In step two "Authorize an Account" in the "Link your account" section, step 1, you are instructed to "open the following link in a web browser":

### ISSUE THREAD

**Issue by zzack01** [potmat/homebridge-google-nest-sdm#39]
This url does not work:

You should instead use this URL:

https://nestservices.google.com/partnerconnections/project-id/auth?redirect_uri=https://www.google.com&access_type=offline&prompt=consent&client_id=oauth2-client-id&response_type=code&scope=https://www.googleapis.com/auth/sdm.service+https://www.googleapis.com/auth/pubsub

**Comment by potmat** [comment]
This seems identical to the URL in the readme, unless I'm missing something.

**Comment by zzack01** [comment]
Hello,

Yes this is the correct url, however when I attempted to do it myself and with someone, it shows:
Something went wrong
Please contact the developer of this app if the issue persists.

**Comment by zzack01** [comment]
By any chance do you have a follow along youtube video of how to do the setup?

**Comment by potmat** [comment]
I don't, however if you look in the FAQ I provide a link to the guide for Home Assistant, which is very similar, along with links to the Reddit and Discord channels.  I'm very sorry but I can't provide support for going through the process with Google.
