### ISSUE TITLE
Curl - error: "invalid_grant"

### ISSUE THREAD

**Issue by tonywc** [potmat/homebridge-google-nest-sdm#49]
Hello,

I'm trying to figure out what I did wrong here. I've gone over the instructions multiple times but every time I run the curl command I get

"error": "invalid_grant",
"error_description": "Bad Request"

I've literally copied what was on the google page after filling in the information from the other steps.

**Comment by potmat** [comment]
Hi @tonywc, if this is an issue with getting through the Google getting started guide I'm afraid I can't provide support for that. You can also try reaching out to others on [Discord](https://discord.gg/kqNCe2D) or [Reddit](https://www.reddit.com/r/homebridge/), some people there may be able to help.

**Comment by nefariouslegion** [comment]
@tonywc I'm currently having this issue. Wondering if you ever figured out a fix?

**Comment by drax16** [comment]
@potmat I'm also struggling with this issue. I've scratched everything and started over twice (in case I made any errors on the way), but the result is the same. I appreciate your work on this plugin!

**Comment by drax16** [comment]
@nefariouslegion @tonywc Did you guys ever find a resolution to this?

**Comment by schtee11** [comment]
@nefariouslegion @tonywc @drax16 Did y'all ever get this working?
