### ISSUE TITLE
Camera feed drops

### ISSUE THREAD

**Issue by futandrew** [potmat/homebridge-google-nest-sdm#58]
The camera feed rarely works. Most of the time is just a white background with a blue NEST logo. 

Log says 
`[homebridge-google-nest-sdm] FFmpeg exited with code: 1 and signal: null (Error) My DORMITORY Camera`

**Comment by nefariouslegion** [comment]
@futandrew Just wondering if you fixed this and if so how? Because I'm having the same issue

**Comment by futandrew** [comment]
> @futandrew Just wondering if you fixed this and if so how? Because I'm having the same issue

No, I didn't fix it, but found that the issue is mentioned in the readme doc. Give it a try and you may fix it.
