### ISSUE TITLE
Plugin initialization failed Every 7 days 

### ISSUE THREAD

**Issue by Beuk14** [potmat/homebridge-google-nest-sdm#60]
I always need to renew my refresh token every 7 days. 
Is there something I can do to prevent this? 

Thanks,
Matthias

**Comment by potmat** [comment]
I've never seen this before... I've been using the same token for years.  What message do you get?

**Comment by allenporter** [comment]
This typically means your oauth consent screen is set to `testing` instead of `production` in the google cloud console. See https://support.google.com/cloud/answer/10311615 for more under `Publishing Status` and `Testing`

**Comment by potmat** [comment]
@Beuk14 : Let us know if this helps.

**Comment by Beuk14** [comment]
Yes, this did it for me!
Thank you for the response!
