### ISSUE TITLE
Plugin initialization failed, there was a failure with event subscription. Did you read the readme: https://github.com/potmat/homebridge-google-nest-sdm#where-do-the-config-values-come-from StatusError: User not authorized to perform this action

### ISSUE THREAD

**Issue by Hackintoshbigsur** [potmat/homebridge-google-nest-sdm#61]
I have been trying for months and everytime I reset these values I still get this error.

**Comment by Hackintoshbigsur** [comment]
I had to create a new event subscription with AllUsers Prinicple Permission enabled with the topic ID of the Nest SDM pub/sub.

**Comment by gregwym** [comment]
Hi @tealtwo could you elaborate on how to create a new event subscription with AllUsers Principle Permission?

**Comment by tealtwo** [comment]
i went under permissions in the pu/sub topic id
