### ISSUE TITLE
ERROR Failed to start stream: input to ffmpeg was provides as stdin, but the process does not support stdin

### ISSUE THREAD

**Issue by tealtwo** [potmat/homebridge-google-nest-sdm#62]
It records too late because of the error in the title, which results in no hksv recordings.

**Comment by psdl-dev** [comment]
I have the same problem.

**Comment by jrbaker87** [comment]
Same problem here too. Still trying to find a solution. I have noticed it sometimes is followed by:

Failed to start stream: input to ffmpeg was provides as stdin, but the process does not support stdin.

[HDS ::ffff:**IP ADDRESS**] Recording download stream 1 is still awaiting generator although stream was closed 10s ago! This is a programming mistake by the camera implementation which prevents freeing up resources.

Don't know if it is coincidence or the two errors are related but more often than not, I get the two messages together. The IP address for the second error is for my appleTV not my doorbell.

**Comment by tealtwo** [comment]
The ip address is their so your apple tv can analyze the clip to see if there was any motion there to record hksv. IMO Starling Home Hub Is better, you should just bite the bullet and buy one.

**Comment by jrbaker87** [comment]
An ok thanks. Relatively new to all this. I'll check that out.

**Comment by potmat** [comment]
What environment are you running the plugin on?

**Comment by jrbaker87** [comment]
I'm running homebridge in a docker container on an Unraid server.

**Comment by potmat** [comment]
We've seen problems like this in the past with that exact setup that were resolved by running Homebridge on a host directly (such as an RPi) on the local network.  It seems that the WebRTC stream has problems with the networking associated with such as setup:  https://github.com/potmat/homebridge-google-nest-sdm/issues/43

**Comment by jrbaker87** [comment]
Ok I'll give that a try. Thanks for the assistance.

**Comment by jrbaker87** [comment]
> We've seen problems like this in the past with that exact setup that were resolved by running Homebridge on a host directly (such as an RPi) on the local network.  It seems that the WebRTC stream has problems with the networking associated with such as setup:  https://github.com/potmat/homebridge-google-nest-sdm/issues/43

This fixed the issue. Many thanks.
