### ISSUE TITLE
Failed to start stream: spawn ffmpeg ENOENT

### ISSUE THREAD

**Issue by nilsou** [potmat/homebridge-google-nest-sdm#63]
I have a valid ffmpeg installed but I'm still getting `Failed to start stream: spawn ffmpeg ENOENT` every time I try to start streaming. Any idea what might be going on?

**Comment by potmat** [comment]
Please see the third question of the FAQ.

Q: My cameras never respond. Why?

A: There are a couple possible reasons for this:

Do you see something like [homebridge-google-nest-sdm] Failed to start stream: spawn ffmpeg ENOENT in your logs? The plugin requires ffmpeg and tries to auto-install it, but if it can't, you'll have to install it manually. For Windows go [here](https://www.ffmpeg.org/download.html). If you have a Mac, especially an Apple Silicon Mac, you should probably use [brew](https://formulae.brew.sh/formula/ffmpeg). On Linux use the package manager of your choice.
