### ISSUE TITLE
Stream video not direct

### ISSUE THREAD

**Issue by zifou2015** [potmat/homebridge-google-nest-sdm#73]
Hello 
I configured my plugin , i have all accessories (sensor,temperature and camera ) in my HomeKit .

but in my HomeKit for my camera Google , i dont have stream video in my thumbnail.
I have picture Google , for look stream video i need to click in my thumbnail.

how to get live video stream?

![A0AA35ED-6DF8-43DB-983C-0A28AD4A882B](https://user-images.githubusercontent.com/16462182/221683523-ed4c552a-df5c-4d4b-a13e-acaf90590641.jpeg)

**Comment by potmat** [comment]
Please refer to the [FAQ](https://github.com/potmat/homebridge-google-nest-sdm#faq):

```
Q: I don't see camera snapshots in the Home app, just the Nest/Google logo. Why?

A: The SDM API does not have any method for getting a camera snapshot on demand, only when an event occurs. The Nest logo is used as a placeholder for first generation cameras, while the Google logo is used for second generation cameras. If an event occurred in the last few seconds you will likely see an image.
```
