### ISSUE TITLE
Turning off Nest camera

### ISSUE THREAD

**Issue by KoenVestjens** [potmat/homebridge-google-nest-sdm#83]
So in the native Google Home app you can turn off the camera using the 'Away' or 'Home' routine. What I would like to achieve is to turn off the camera using HomeKit. I have created a dummy switch using [homebridge-dummy](https://www.npmjs.com/package/homebridge-dummy) called 'alarm'. When the switch 'alarm' is on I would like to have the camera on. When 'alarm' is off, the camera should be off too.

Maybe I'm not looking at the correct location in HomeKit, or it's not even possible. Maybe there are workarounds to make this work, like starting a custom routine in the Google Home app using HomeKit. Who can help me out?

**Comment by potmat** [comment]
Hi @KoenVestjens, unfortunately the SDM API does not offer any method to turn the cameras on or off.

Regarding having HomeKit run a routine in the Google Home app, I have my doubts, but at any rate that is outside the scope of this plugin.
