### ISSUE TITLE
Issue getting refresh token

### ISSUE THREAD

**Issue by nefariouslegion** [potmat/homebridge-google-nest-sdm#88]
Hi,
Currently trying to setup the plugin and I'm at the part where I try to get the refresh token.
![image](https://github.com/potmat/homebridge-google-nest-sdm/assets/89366675/c8c8dc39-bb81-4293-b8ce-99ff9d839c83)

However when I enter that command into a Windows 11 terminal I get the following error 
![image](https://github.com/potmat/homebridge-google-nest-sdm/assets/89366675/c7c39796-6a5b-468b-96d4-c176b0d4a408)

I then tried it in a Git bash terminal and got a different output: 
![image](https://github.com/potmat/homebridge-google-nest-sdm/assets/89366675/359edc08-54db-47e2-a725-0ef740ff3e2b)

I also tried entering the command in the homebridge terminal and it just outputs this: 
![image](https://github.com/potmat/homebridge-google-nest-sdm/assets/89366675/3c8dcfe8-645d-4eee-8481-b155c32bcc38)

None of these match what the website says the output should be. So I'm not sure what I'm doing wrong or where I should be trying to enter this command? Any help would be appreciated greatly

**Comment by nefariouslegion** [comment]
Issue resolved. Tried again and it worked

**Comment by PhilTheNewbie** [comment]
Hi,
I have the same issue.
Tried Terminal on both Mac and Homebridge (NAS). Same response on both machines.
Can you help or point me to literature that may help me resolve it please?
Thank you.
