### ISSUE TITLE
Paid google and the app is blocked

### ISSUE THREAD

**Issue by YutaTheTraveler** [potmat/homebridge-google-nest-sdm#90]
Why is this app blocked? I feel extremely ripped off since I paid and waisted time and this app is blocked

**Comment by YutaTheTraveler** [comment]
Error 400: redirect_uri_mismatch

**Comment by YutaTheTraveler** [comment]
https://nestservices.google.com/partnerconnections/project-id/auth?redirect_uri=https://www.google.com&access_type=offline&prompt=consent&client_id=oauth2-client-id&response_type=code&scope=https://www.googleapis.com/auth/sdm.service

Unable to get an authorization code because this app is blocked

**Comment by potmat** [comment]
Hi @YutaTheTraveler, this is not an "app" that Google can "block" in any sense.  When you run this as a plugin on Homebridge YOU are creating the "app" and authorizing it through your own account.  Please post a screenshot of what you see.

**Comment by YutaTheTraveler** [comment]
> Hi @YutaTheTraveler, this is not an "app" that Google can "block" in any sense. When you run this as a plugin on Homebridge YOU are creating the "app" and authorizing it through your own account. Please post a screenshot of what you see.

Following this: https://developers.google.com/nest/device-access/authorize

**Comment by YutaTheTraveler** [comment]
https://ibb.co/8DhKXs7

Results in this

https://ibb.co/YTByJnp

**Comment by YutaTheTraveler** [comment]
Even manually creating a project in google cloud does not bypass app request being blocked

**Comment by allenporter** [comment]
You likely need to set the authorized redirect urls (e.g. like in https://developers.google.com/nest/device-access/get-started#set_up_google_cloud_platform)

**Comment by YutaTheTraveler** [comment]
> You likely need to set the authorized redirect urls (e.g. like in https://developers.google.com/nest/device-access/get-started#set_up_google_cloud_platform)

‘I’ve done these steps with the oauth given there and one setup in google cloud

**Comment by YutaTheTraveler** [comment]
Added accounts.google.com and googleapis.com as authorized redirect Uris

**Comment by YutaTheTraveler** [comment]
> Added accounts.google.com and googleapis.com as authorized redirect Uris

This seems to have fixed the issue

**Comment by potmat** [comment]
Thank you for your help @allenporter!
