### ISSUE TITLE
Disable Accessories

### ISSUE THREAD

**Issue by ellisonpatterson** [potmat/homebridge-google-nest-sdm#91]
I am using openwrt for my homebridge server, and since the server is just a consumer router, ffmpeg has no chance of running without severe performance issues.

Is there a way to disable cameras but keep other accessories available?

Thank you!

**Comment by potmat** [comment]
Hi @ellisonpatterson, yes this is no problem. When you are going through the setup process and visit the ["ONE IMPORTANT DIFFERENCE"](https://github.com/potmat/homebridge-google-nest-sdm#where-do-the-config-values-come-from) URL you can choose which Nest devices to authorize, if you don't include any cameras then they won't show up.

**Comment by ellisonpatterson** [comment]
Thank you that worked!
