### ISSUE TITLE
error when getting the token

### ISSUE THREAD

**Issue by julianborghuis** [potmat/homebridge-google-nest-sdm#95]
Hello,

I tried to get an token but i dont get it to work.
I am getting the error code No access to partner
Information cannot be retrieved. Please contact scrypted to check whether your account is set up correctly. You may need to add the developer's email address as a member of your home in the Google Home app's settings.

I also  added my email to the test users.
I am the home owner. what can i do?

**Comment by potmat** [comment]
Hi @julianborghuis, as it says in the FAQ:

Q: I'm having problems getting through the getting started guide and getting the config values. Can you help?

A: Probably not. Having a day job and family I don't have much time to help with this. The Nest plugin for Home Assistant uses much the same process (don't forget the ["ONE IMPORTANT DIFFERENCE"](https://github.com/potmat/homebridge-google-nest-sdm#where-do-the-config-values-come-from) section above). It has an [illustrated guide](https://www.home-assistant.io/integrations/nest/) that you may find helpful. You can also try reaching out to others in [Discussions](https://github.com/potmat/homebridge-google-nest-sdm/discussions), on [Discord](https://discord.gg/kqNCe2D), or [Reddit](https://www.reddit.com/r/homebridge/), some people there may be able to help.
